name: "Terraform plan staging"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terragrunt/**"
      - "!terragrunt/env/production/**"
      - ".github/workflows/tf_plan_staging.yml"

env:
  AWS_REGION: ca-central-1
  TERRAFORM_VERSION: 1.11.2
  TERRAGRUNT_VERSION: 0.75.6
  TF_VAR_mongodb_uri: ${{ secrets.MONGODB_URI }}
  TF_VAR_airtable_api_key: ${{ secrets.AIRTABLE_API_KEY }}
  TF_VAR_google_service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
  TF_VAR_airtable_base: ${{ secrets.AIRTABLE_BASE }}
  TF_VAR_health_airtable_base: ${{ secrets.HEALTH_AIRTABLE_BASE }}
  TF_VAR_cra_airtable_base: ${{ secrets.CRA_AIRTABLE_BASE }}
  TF_VAR_travel_airtable_base: ${{ secrets.TRAVEL_AIRTABLE_BASE }}
  TF_VAR_ircc_airtable_base: ${{ secrets.IRCC_AIRTABLE_BASE }}

permissions:
  id-token: write
  contents: read
  pull-requests: write
  actions: write
  checks: write
  statuses: write

jobs:
  terraform-plan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - module: network
          - module: ecr
          - module: ssm
          - module: iam
          - module: ecs
          - module: eventbridge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform Tools
        uses: cds-snc/terraform-tools-setup@v1

      - name: Configure aws credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::992382783569:role/dto-feedback-cj-plan
          role-session-name: TFPlan
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform plan
        uses: cds-snc/terraform-plan@v3.3.2
        with:
          comment-delete: true
          comment-title: "Staging: ${{ matrix.module }}"
          directory: ./terragrunt/env/staging/${{ matrix.module }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          terragrunt: true
